### PR TITLE
test bumpwq

### PR DESCRIPTION
**Pull request by bernt-matthias**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Midnighter** [comment]
It's probably time for another cobra release soon anyway but thank you for working on this. I'll review when CI passes.

**Comment by bernt-matthias** [comment]
Thanks @Midnighter .

I stumbled over this because we get `ImportError: cannot import name 'print_dependencies' from 'depinfo' (/usr/local/lib/python3.9/site-packages/depinfo/__init__.py)` for the `rpbasicdesign` package in a weekly Galaxy tool test.

Would this solve this?

**Review by Midnighter — APPROVED** [review]
Thanks for fixing the recipe. How did you come across this? There already exists the conda package for cobra 0.25, right?

**Comment by bernt-matthias** [comment]
The full Traceback of our test is: 

```
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/rpbasicdesign/cli.py", line 14, in <module>
    from rpbasicdesign.Designer import Designer
  File "/usr/local/lib/python3.9/site-packages/rpbasicdesign/Designer.py", line 23, in <module>
    from rptools.rplibs import rpSBML, rpPathway
  File "/usr/local/lib/python3.9/site-packages/rptools/rplibs/__init__.py", line 7, in <module>
    from rptools.rplibs.rpPathway import rpPathway
  File "/usr/local/lib/python3.9/site-packages/rptools/rplibs/rpPathway.py", line 46, in <module>
    from .rpSBML import rpSBML
  File "/usr/local/lib/python3.9/site-packages/rptools/rplibs/rpSBML.py", line 40, in <module>
    import cobra
  File "/usr/local/lib/python3.9/site-packages/cobra/__init__.py", line 5, in <module>
    from cobra.core import (
  File "/usr/local/lib/python3.9/site-packages/cobra/core/__init__.py", line 1, in <module>
    from cobra.core.configuration import Configuration
  File "/usr/local/lib/python3.9/site-packages/cobra/core/configuration.py", line 16, in <module>
    from cobra.util.solver import interface_to_str
  File "/usr/local/lib/python3.9/site-packages/cobra/util/__init__.py", line 4, in <module>
    from cobra.util.util import *
  File "/usr/local/lib/python3.9/site-packages/cobra/util/util.py", line 6, in <module>
    from depinfo import print_dependencies
ImportError: cannot import name 'print_dependencies' from 'depinfo' (/usr/local/lib/python3.9/site-packages/depinfo/__init__.py)
```

**Pull request merged**
